### ISSUE TITLE
Babel Broke Ma Authorization

### ISSUE THREAD

**Issue by IanMitchell** [IanMitchell/ARX-7#121]
```
/Users/ianm/Code/ARX-7/node_modules/irc/lib/irc.js:751
                        throw err;
                        ^

TypeError: listener must be a function
    at Client.removeListener (events.js:276:15)
    at Client.callbackWrapper (arx7.js:161:23)
    at emitMany (events.js:108:13)
    at Client.emit (events.js:182:7)
    at Client.<anonymous> (/Users/ianm/Code/ARX-7/node_modules/irc/lib/irc.js:245:22)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator (/Users/ianm/Code/ARX-7/node_modules/irc/lib/irc.js:748:26)
    at Array.forEach (native)
    at Socket.<anonymous> (/Users/ianm/Code/ARX-7/node_modules/irc/lib/irc.js:743:15)
```

Looks like Babel 6 destroyed the `isAuthorized` method.

**Comment by IanMitchell** [comment]
Side note, Jukey points out Line 115 on ARX-7 should be `return resolve();`

**Comment by IanMitchell** [comment]
Turns out, this was always broken - it was getting suppressed for some reason earlier.
