### ISSUE TITLE
Exception Error Thrown (Don't Know Context)

### ISSUE THREAD

**Issue by BlueCrystal** [IanMitchell/ARX-7#54]
So this happened. Dunno if you're able to tell what occurred but have an exception error:

belfiore@souma:~/ARX-7$ node app.js
/home/belfiore/ARX-7/node_modules/irc/lib/irc.js:748
                        throw err;
                        ^

TypeError: Cannot read property 'includes' of undefined
    at ARX7.message (/home/belfiore/ARX-7/src/arx7.js:84:29)
    at Client.<anonymous> (/home/belfiore/ARX-7/src/bot.js:28:8)
    at emitMany (events.js:108:13)
    at Client.emit (events.js:182:7)
    at Client.<anonymous> (/home/belfiore/ARX-7/node_modules/irc/lib/irc.js:517:22)
    at emitOne (events.js:77:13)
    at Client.emit (events.js:169:7)
    at iterator (/home/belfiore/ARX-7/node_modules/irc/lib/irc.js:745:26)
    at Array.forEach (native)
    at Socket.<anonymous> (/home/belfiore/ARX-7/node_modules/irc/lib/irc.js:740:15)

**Comment by IanMitchell** [comment]
Need to start it with `npm start` rather than `node app.js`
